---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configmap
  labels:
    {{- include "reporting-service.labels" . | nindent 4 }}
data:
  nginx.conf : |-{{ .Files.Get "nginx/nginx.conf" | indent 4}}
  {{- if eq .Values.environment "staging" }}
  reporting-service.trader.adgear.com.conf : |-{{ .Files.Get "nginx/reporting-service-staging.trader.adgear.com.conf" | indent 4}}
  {{- end }}
  adgear_reporting_trusted.conf : |-{{ .Files.Get "nginx/adgear_reporting_trusted.conf" | nindent 4 }}
  adgear_reporting_service.conf :  |-{{ .Files.Get "nginx/adgear_reporting_service.conf" | indent 4}}
  {{- if eq .Values.environment "prod" }} 
  reporting-service.trader.adgear.com.conf : |-{{ .Files.Get "nginx/reporting-service-prod.trader.adgear.com.conf" | indent 4}}
  {{- end }}
