apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "reporting-service.fullname" . }}-secret
data:
  {{- range $key, $value := .Values.vault }}
  {{ $key }}:  {{ $value | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.vertica }}
  {{ $key }}:  {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.cronjob }}
  {{ $key }}:  {{ $value | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.cronjob_base64 }}
  {{ $key }}:  {{ $value | quote }}
  {{- end }}

