---
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reporting-service.fullname" . }}-api-internal
  labels:
    {{- include "reporting-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  selector:
    {{- include "reporting-service-api.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reporting-service.fullname" . }}-internal
  labels:
    {{- include "reporting-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  selector:
    {{- include "reporting-service.selectorLabels" . | nindent 4 }}
{{- end }}
